apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: 'https://github.com/mcconnellj/server'
    targetRevision: production
    path: apps
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true