apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mcconnellj/server
  password: ${{ secrets.GIT_USERNAME }}
  username: ${{ secrets.GIT_PASSWORD }}
  project: default