- name: Initialize linux host
  hosts: linux  # Targets the 'linux' group (only 'tower' in this case)
  gather_facts: true
  become: true
  roles:
    - role: linux-prereq

- name: Initialize proxmox host
  hosts: proxmox  # Targets the 'proxmox' group (all-in-one and wyze1-wyze5)
  gather_facts: true
  become: true
  roles:
    - role: proxmox-prereq

- name: Initialize wyze-specific configurations
  hosts: wyze  # Targets the 'wyze' group (wyze1-wyze5)
  gather_facts: true
  become: true
  roles:
    - role: wyze

- name: Initialize tower-specific configurations
  hosts: tower  # Targets the 'tower' host
  gather_facts: true
  become: true
  roles:
    - role: tower

- name: Initialize all-in-one-specific configurations
  hosts: all-in-one  # Targets the 'all-in-one' host
  gather_facts: true
  become: true
  roles:
    - role: all-in-one

- name: Initialize K3s server node
  hosts: k3s-server  # Targets the 'k3s-server' group (all-in-one, wyze1-wyze3)
  gather_facts: true
  become: true
  roles:
    - role: k3s-server

- name: Initialize K3s agent node
  hosts: k3s-agent  # Targets the 'k3s-agent' group (wyze4-wyze5)
  gather_facts: true
  become: true
  roles:
    - role: k3s-agent