apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    name: in-cluster
  project: development
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 'v1.11.0'
    helm:
    
      parameters:
        - name: installCRDs
          value: 'true'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

#helm repo add argo https://argoproj.github.io/argo-helm
#helm install my-argo-cd argo/argo-cd --version 7.8.2