services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file:
      - .env
    environment:
      - DOMAIN=https://${VAULTWARDEN_SUBDOMAIN}.${DOMAIN}
    volumes:
      - vw-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver"
    networks:
      - traefik-net
      - internal-net
    restart: unless-stopped

  firefly-iii:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - traefik-net
      - internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-iii.rule=Host(`${FIREFLY_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.firefly-iii.entrypoints=websecure"
      - "traefik.http.routers.firefly-iii.tls.certresolver=myresolver"
    depends_on:
      - mariadb  # Corrected to match the service name

  mariadb:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - internal-net
    volumes:
      - firefly_iii_db:/var/lib/mysql

  traefik:
    image: traefik:latest
    container_name: traefik
    env_file:
      - .env
    command:
      - "--providers.docker=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
    networks:
      - traefik-net
    restart: unless-stopped

volumes:
  vw-data:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  traefik-net:
  internal-net:
    driver: bridge