global:
  image:
    tag: "v2.6.6"

server:
  extraArgs:
  - --insecure
  - --create-namespace
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  metrics:
    enabled: true

redis:
  exporter:
    enabled: true

applicationSet:
  enabled: true

configs:
  secret:
    argocdServerAdminPassword: "h3ll0world" # real password is here
  repositories:
    server:
      url: https://github.com/mcconnellj/server
      type: git
      password: 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
      username: josh.v.mcconnell@gmail.com